conditioning:
  method: ps
  params:
    scale: 0.5

data:
  name: celebhq
  root: ./data/samples_celebhq/
  size: [256, 256]
  
measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: random
    # mask_len_range: !!python/tuple [128, 129]  # for box
    mask_prob_range: [0.3,0.7] #!!python/tuple [0.3, 0.7]  # for random
    image_size: 256


  noise:
    name: gaussian
    sigma: 0.05
