conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: celebhq
  root: ./data/samples_celebhq/
  size: [256, 256]

measurement:
  operator:
    name: super_resolution
    in_shape: [1, 3, 256, 256]   #!!python/tuple [1, 3, 256, 256]
    scale_factor: 4
  
  noise: 
    name: gaussian
    sigma: 0.05
