conditioning:
  method: ps
  params:
    scale: 0.3

  # for ddim
  # method: pg
  # params:
  #   scale: 10.
  #   mc: 1000
  #   beta: 0.0

  # # for ddpm
  # method: pg
  # params:
  #   scale: 30.
  #   mc: 500
  #   beta: 0.
  #   bias: 0.
  #   rmin: 0.1


data:
  name: ffhq
  root: /home/tanghaoyue13/dataset/ffhqvaldps

measurement:
  operator:
    name: color
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4

  noise:
    name: gaussian
    sigma: 0
    # sigma: 0.

    # sigma: 0.05
