sampler: ddim
steps: 1000
noise_schedule: linear
rescale_timesteps: False
model_mean_type: epsilon
model_var_type: learned_range
dynamic_threshold: False
clip_denoised: True
timestep_respacing: ddim100
