conditioning:
  # method: ps
  # params:
  #   scale: 0.4

  # ddpm
  # params:
  #   scale: 200.
  #   mc: 500
  #   beta: 0.0

  # ---DDIM 200
  method: pg
  params:
    scale: 150.
    mc: 1500
    beta: 0.0

data:
  name: imagenet
  root: /home/tanghaoyue13/dataset/dataset


measurement:
  operator:
    name: gaussian_blur
    kernel_size: 61
    intensity: 3.0

  noise:
    # name: poisson
    # rate: 1.0
    name: gaussian
    sigma: 0.05
