conditioning:
  # method: ps
  # params:
  #   scale: 0.5
  # method: pg
  # params:
  #   scale: 1.
  #   mc: 10000
  #   beta: 0.1
  # DDIM
  method: pg
  params:
    scale: 3.
    mc: 11000
    beta: 0.1

data:
  name: ffhq
  root: /home/tanghaoyue13/dataset/ffhqval

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: box
    mask_len_range: !!python/tuple [128, 129]  # for box
    image_size: 256


  noise:
    name: gaussian
    sigma: 0.05
