conditioning:
  # for poisson
  # method: ps
  # params:
  #   scale: 0.2

  # # for Gaussian noise DDPM
  # method: pg
  # params:
  #   scale: 200.
  #   mc: 500
  #   beta: 0.
  #   bias: 0.
  #   rmin: 0.05

  # ddim
  method: pg
  params:
    scale: 100.
    mc: 4000
    beta: 0.
    bias: 0.
    rmin: 0.05



data:
  name: imagenet
  root: /home/tanghaoyue13/dataset/dataset


measurement:
  operator:
    name: motion_blur
    kernel_size: 61
    intensity: 0.5

  noise:
    name: gaussian
    sigma: 0.05
