conditioning:
  method: ps
  params:
    scale: 0.4
  # method: pg
  # params:
  #   scale: 150.
  #   mc: 500
  #   beta: 0.

data:
  name: ffhq
  root: /home/tanghaoyue13/dataset/ffhqvaldps

  # root: ./data/samples/

measurement:
  operator:
    name: nonlinear_blur
    opt_yml_path: ./bkse/options/generate_blur/default.yml

  noise:
    name: gaussian
    sigma: 0.05
