conditioning:
  # method: ps
  # params:
  #   scale: 1.

  # # for ddpm, gaussian and poisson noise
  # method: pg
  # params:
  #   scale: 160.
  #   mc: 500
  #   beta: 0.
  #   bias: 0.
  #   rmin: 0.05

  # for DDIM accelerator
  method: pg
  params:
    scale: 80.
    mc: 5000
    beta: 0.
    bias: 0.
    rmin: 0.05


data:
  name: imagenet
  root: /home/tanghaoyue13/dataset/dataset
  # name: uscsipi
  # root: /home/tanghaoyue13/dataset/uscsipi

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4

  noise:
    name: gaussian
    sigma: 0.05
    # name: poisson
    # rate: 1.0

    # sigma: 0.

    # sigma: 0.05
