conditioning:
  # method: ps
  # params:
  #   scale: 1.

  # # DDPM, LPIPS~0.216
  # method: pg
  # params:
  #   scale: 102.
  #   mc: 1000
  #   beta: 0.
  #   bias: 30.72
  #   rmin: 0.05
  #   # notice, bias go with noise

  # # DDPM, LPIPS~0.217
  method: pg
  params:
    scale: 120.
    mc: 800
    beta: 0.
    bias: 0.
    rmin: 0.05

data:
  name: ffhq
  # root: /home/tanghaoyue13/dataset/ffhqval
  root: /home/tanghaoyue13/dataset/ffhqvaldps
  # root: ./data/ffhq

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4

  noise:
    name: gaussian
    sigma: 0.05
    # sigma: 0.05
