conditioning:
  # method: ps
  # params:
  #   scale: 1.

  # # DDPM, LPIPS~0.217, average pooling gaussian, scale 120, mc 800
  method: pg
  params:
    scale: 2000.
    mc: 500
    beta: 0.
    bias: 0.
    rmin: 0.05

data:
  name: ffhq
  root: /home/tanghaoyue13/dataset/ffhqvaldps

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4

  noise:
    # name: poisson
    # rate: 1.0
    name: gaussian
    sigma: 0.05
    # sigma: 0.05
