conditioning:
  method: ps
  params:
    scale: 1.

  # for ddim
  # method: pg
  # params:
  #   scale: 10.
  #   mc: 1000
  #   beta: 0.0

  # # for ddpm
  # scale 150, mc 800, ~0.377
  # scale 80, mc 800, ~0.399
  # scale 100, mc 500, ~0.38
  # scale 150, mc 500, ~0.323, bias 30.72 very good
  # method: pg
  # params:
  #   scale: 160.
  #   mc: 500
  #   beta: 0.
  #   bias: 0.
  #   rmin: 0.05


data:
  name: imagenet
  root: .results/ddpm/super_resolution_imagenet_pg/label
  # root: /home/tanghaoyue13/dataset/dataset

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4

  noise:
    name: gaussian
    sigma: 0.05
    # sigma: 0.

    # sigma: 0.05
